version: '3.1'
services:
  app:
    extra_hosts:
        host.docker.internal: host-gateway
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: movie_app
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: movie_archive
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend
  mysql:
    image: mysql:5.6
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: movie_archive
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  

    